language: node_js
node_js:
  - 12
before_script:
  - npm run setup
  - npm run build
deploy:
  provider: elasticbeanstalk
  access_key_id: ACCESSKEYID
  secret_access_key: SECRETACCESSKEYID
  region: 'eu-central-1'
  app: 'p'
  env: 'P-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-564167133035'
